/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Wed Aug  1 18:07:08 2018. */

#ifndef PB_STRIP_PB_H_INCLUDED
#define PB_STRIP_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Strip_Animation {
    Strip_Animation_NONE = 0,
    Strip_Animation_COLORLOOP = 1,
    Strip_Animation_COLORFADE = 2
} Strip_Animation;
#define _Strip_Animation_MIN Strip_Animation_NONE
#define _Strip_Animation_MAX Strip_Animation_COLORFADE
#define _Strip_Animation_ARRAYSIZE ((Strip_Animation)(Strip_Animation_COLORFADE+1))

/* Struct definitions */
typedef struct _Strip_Led {
    int32_t num;
    uint32_t rgbw;
/* @@protoc_insertion_point(struct:Strip_Led) */
} Strip_Led;

typedef struct _Strip_Whole_Strip {
    uint32_t rgbw;
/* @@protoc_insertion_point(struct:Strip_Whole_Strip) */
} Strip_Whole_Strip;

typedef struct _Strip {
    bool has_brt;
    int32_t brt;
    bool has_whole;
    Strip_Whole_Strip whole;
    pb_callback_t leds;
    bool has_animation;
    Strip_Animation animation;
/* @@protoc_insertion_point(struct:Strip) */
} Strip;

/* Default values for struct fields */
extern const Strip_Animation Strip_animation_default;

/* Initializer values for message structs */
#define Strip_init_default                       {false, 0, false, Strip_Whole_Strip_init_default, {{NULL}, NULL}, false, Strip_Animation_NONE}
#define Strip_Led_init_default                   {0, 0}
#define Strip_Whole_Strip_init_default           {0}
#define Strip_init_zero                          {false, 0, false, Strip_Whole_Strip_init_zero, {{NULL}, NULL}, false, _Strip_Animation_MIN}
#define Strip_Led_init_zero                      {0, 0}
#define Strip_Whole_Strip_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define Strip_Led_num_tag                        1
#define Strip_Led_rgbw_tag                       2
#define Strip_Whole_Strip_rgbw_tag               1
#define Strip_brt_tag                            1
#define Strip_whole_tag                          2
#define Strip_leds_tag                           3
#define Strip_animation_tag                      4

/* Struct field encoding specification for nanopb */
extern const pb_field_t Strip_fields[5];
extern const pb_field_t Strip_Led_fields[3];
extern const pb_field_t Strip_Whole_Strip_fields[2];

/* Maximum encoded size of messages (where known) */
/* Strip_size depends on runtime parameters */
#define Strip_Led_size                           16
#define Strip_Whole_Strip_size                   5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define STRIP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
